language: python
cache: pip
python:
- 3.8
- 3.9
- 3.9-dev
- nightly
dist: xenial

before_install:
  - python3 -m pip install coverage
install:
  - python3 -m pip install -U -r dev-requirements.txt
script:
  - python3 -m coverage run --branch -m pytest tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
