[pytest]
addopts =
    --strict-config
    --strict-markers
    --cov blurb_it
    --cov tests
    --cov-report html
    --cov-report term
    --cov-report xml
xfail_strict = True
asyncio_mode = auto
filterwarnings =
    error
    # Pending https://github.com/aio-libs/aiohttp-session/pull/1204
    ignore::aiohttp.web_exceptions.NotAppKeyWarning
testpaths =
    tests
